Repository Accenture/sfpowerkit, pull requests merged in 2020-07, with the labels that each got.

#317 Fix error handling
  src/impl/package/version/packageInfo.ts
Labels: bug

#325 Fix missing log files in Scratch Org create command
  package.json
  src/impl/pool/scratchorg/poolCreateImpl.ts
Labels: bug

#330 DataModel Diff
  README.md
  messages/project_datamodel_diff.json
  npm-shrinkwrap.json
  oclif.manifest.json
  package.json
  src/commands/sfpowerkit/project/datamodel/diff.ts
  src/impl/package/version/packageInfo.ts
  src/impl/pool/scratchorg/poolCreateImpl.ts
  src/impl/project/metadata/DataModelSourceDiffImpl.ts
  src/impl/project/metadata/diffgenerators/diffGenerator.ts
  src/impl/project/metadata/diffgenerators/export.ts
  src/impl/project/metadata/diffgenerators/sourceDiffGenerator.ts
  yarn.lock
Labels: new feature

#328 Update package:valid to use v49 of the metadata coverage report
  resources/metadata.json
  src/commands/sfpowerkit/package/valid.ts
Labels: enhancement

#334 Share a pooled scratch org with another DevHub user
  README.md
  messages/scratchorg_poolFetch.json
  npm-shrinkwrap.json
  oclif.manifest.json
  package.json
  src/commands/sfpowerkit/pool/fetch.ts
  src/impl/pool/scratchorg/poolFetchImpl.ts
  src/utils/getUserDetails.ts
  src/utils/scratchOrgUtils.ts
  src_saleforce_packages/scratchorgpool/force-app/main/default/workflows/ScratchOrgInfo.workflow-meta.xml
Labels: enhancement

#335 Add retry capability to fetch installed packages in an org
  npm-shrinkwrap.json
  oclif.manifest.json
  package.json
  src/commands/sfpowerkit/package/dependencies/install.ts
Labels: enhancement

#336 Refactor into packageutils with retry
  npm-shrinkwrap.json
  src/commands/sfpowerkit/dependency/tree/package.ts
  src/commands/sfpowerkit/package/version/info.ts
  src/impl/package/version/packageInfo.ts
  src/utils/packageUtils.ts
Labels: enhancement

#337 Enhancements to Scratch Org Pool
  README.md
  messages/scratchorg_pool_create.json
  oclif.manifest.json
  schemas/pool/so_pool_config_tag_mode.json
  src/commands/sfpowerkit/pool/create.ts
  src/impl/pool/scratchorg/poolCreateImpl.ts
Labels: bug, enhancement
