Repository Accenture/sfpowerkit, pull requests merged in 2020-04, with the labels that each got.

#233 Task/mainfest utils
  README.md
  messages/project_mainfest_diff.json
  messages/project_mainfest_merge.json
  messages/source_customlabel_buildmainfest.json
  npm-shrinkwrap.json
  oclif.manifest.json
  package.json
  src/commands/sfpowerkit/project/mainfest/diff.ts
  src/commands/sfpowerkit/project/mainfest/merge.ts
  src/commands/sfpowerkit/source/customlabel/buildmainfest.ts
  src/commands/sfpowerkit/source/permissionset/generatepatch.ts
  src/commands/sfpowerkit/source/picklist/generatepatch.ts
  src/utils/xmlUtil.ts
Labels: new feature

#235 Issue/228
  src/commands/sfpowerkit/org/duplicaterule/activate.ts
  src/commands/sfpowerkit/org/duplicaterule/deactivate.ts
  src/commands/sfpowerkit/org/matchingrule/activate.ts
  src/commands/sfpowerkit/org/matchingrule/deactivate.ts
  src/commands/sfpowerkit/org/trigger/activate.ts
  src/commands/sfpowerkit/org/trigger/deactivate.ts
  src/commands/sfpowerkit/package/applypatch.ts
  src/utils/checkRetrievalStatus.ts
Labels: bug

#236 refactor readme
  README.md
Labels: documentation

#237 fixing test suite convert bug
  src/commands/sfpowerkit/source/apextestsuite/convert.ts
Labels: bug

#238 fixing test suite convert bug
  src/commands/sfpowerkit/source/apextestsuite/convert.ts
Labels: hotfix

#245 Issue #242
  src/commands/sfpowerkit/source/profile/reconcile.ts
Labels: bug

#246 Remove deprecated commands
  README.md
  messages/package_applypatch.json
  messages/source_permissionset_generatepatch.json
  messages/source_picklist_generatepatch.json
  oclif.manifest.json
  src/commands/sfpowerkit/package/applypatch.ts
  src/commands/sfpowerkit/source/customlabel/buildmanifest.ts
  src/commands/sfpowerkit/source/permissionset/generatepatch.ts
  src/commands/sfpowerkit/source/picklist/generatepatch.ts
Labels: enhancement

#248 fix: Corrected flag apiversion casing
  src/commands/sfpowerkit/org/connectedapp/retrieve.ts
Labels: bug

#254 fix: error messaging on sfdx:org:destruct failure
  src/commands/sfpowerkit/org/destruct.ts
Labels: bug
