Repository Accenture/sfpowerkit, pull requests merged in 2021-12, with the labels that each got.

#598 Feature/header log
  package.json
  src/commands/sfpowerkit/auth/login.ts
  src/commands/sfpowerkit/dependency/tree/package.ts
  src/commands/sfpowerkit/org/cleartestresult.ts
  src/commands/sfpowerkit/org/connectedapp/create.ts
  src/commands/sfpowerkit/org/connectedapp/retrieve.ts
  src/commands/sfpowerkit/org/destruct.ts
  src/commands/sfpowerkit/org/duplicaterule/activate.ts
  src/commands/sfpowerkit/org/duplicaterule/deactivate.ts
  src/commands/sfpowerkit/org/healthcheck.ts
  src/commands/sfpowerkit/org/manifest/build.ts
  src/commands/sfpowerkit/org/matchingrule/activate.ts
  src/commands/sfpowerkit/org/matchingrule/deactivate.ts
  src/commands/sfpowerkit/org/orgcoverage.ts
  src/commands/sfpowerkit/org/orgwideemail/create.ts
  src/commands/sfpowerkit/org/orgwideemail/verify.ts
  src/commands/sfpowerkit/org/profile/diff.ts
  src/commands/sfpowerkit/org/relaxiprange.ts
  src/commands/sfpowerkit/org/sandbox/create.ts
  src/commands/sfpowerkit/org/sandbox/info.ts
  src/commands/sfpowerkit/org/sandbox/refresh.ts
  src/commands/sfpowerkit/org/scratchorg/delete.ts
  src/commands/sfpowerkit/org/scratchorg/usage.ts
  src/commands/sfpowerkit/org/trigger/activate.ts
  src/commands/sfpowerkit/org/trigger/deactivate.ts
  src/commands/sfpowerkit/package/applypatch.ts
  src/commands/sfpowerkit/package/dependencies/install.ts
  src/commands/sfpowerkit/package/dependencies/list.ts
  src/commands/sfpowerkit/package/valid.ts
  src/commands/sfpowerkit/package/version/codecoverage.ts
  src/commands/sfpowerkit/package/version/info.ts
  src/commands/sfpowerkit/pool/create.ts
  src/commands/sfpowerkit/pool/delete.ts
  src/commands/sfpowerkit/pool/fetch.ts
  src/commands/sfpowerkit/pool/list.ts
  src/commands/sfpowerkit/project/datamodel/diff.ts
  src/commands/sfpowerkit/project/diff.ts
  src/commands/sfpowerkit/project/manifest/diff.ts
  src/commands/sfpowerkit/project/manifest/merge.ts
  src/commands/sfpowerkit/project/orgdiff.ts
  src/commands/sfpowerkit/source/apextest/list.ts
  src/commands/sfpowerkit/source/apextestsuite/convert.ts
  src/commands/sfpowerkit/source/customlabel/buildmanifest.ts
  src/commands/sfpowerkit/source/customlabel/create.ts
  src/commands/sfpowerkit/source/customlabel/reconcile.ts
  src/commands/sfpowerkit/source/picklist/generatepatch.ts
  src/commands/sfpowerkit/source/pmd.ts
  src/commands/sfpowerkit/source/profile/merge.ts
  src/commands/sfpowerkit/source/profile/reconcile.ts
  src/commands/sfpowerkit/source/profile/retrieve.ts
  src/commands/sfpowerkit/user/password/generate.ts
  src/sfpowerkit.ts
  src/sfpowerkitCommand.ts
Labels: enhancement

#608 fix(package-valid)!: bypass flag not respected
  src/commands/sfpowerkit/package/valid.ts
Labels: bug, breaking

#609 fix(package-valid)!: property name
  src/commands/sfpowerkit/package/valid.ts
Labels: breaking
